### ISSUE TITLE
MinPlugInstall throws "E739: Cannot create directory" if ~/.vim/pack/plugins/opt exists already

### ISSUE THREAD

**Issue by bbolli** [Jorengarenar/minPlug#1]
I'm using VIM 8.0 (patches 1-1453) on Ubuntu 18.04 LTS, in case this helps.

I've added a `silent!` before the ` call mkdir()` to silence the error.

**Comment by Jorengarenar** [comment]
Looks like the issues was prior to patch 8.0.1708.

Is plugin being installed properly in appropriate location despite the error (so `silent!` will be sufficient) or there is need to make up another solution?

**Comment by bbolli** [comment]
Yes, it worked after adding `silent!`. I guess that the `'p'` parameter didn't the same meaning as in POSIX mkdir(1) before patch 8.0.1708.

**Comment by bbolli** [comment]
Thanks!
