### ISSUE TITLE
minPlug does not respect &plugpath ?

### ISSUE THREAD

**Issue by KKPMW** [Jorengarenar/minPlug#2]
Today I tried to transition from vimplug to minPlug, and found one issue: minPlug, even thou it seems to use `plupath` in the code, does not actually respect the `plugpath`. In particular - it seems to assume that `plugpath` will be composed of multiple directories and substitutes every directory after the first one with `pack/plugins/opt/`.

I am curious if this is intentional or a bug?

**Comment by Jorengarenar** [comment]
I assume you mean the `packpath` option. By default it's composed of multiple directories and it never occurred to me, that minPlug does not handle the case when somebody set it to only one value. It's indeed bug, which I will fix as soon as possible.

**Comment by KKPMW** [comment]
Thank you for fixing this so fast.

The README automatic installation part should probably be updated?

**Comment by Jorengarenar** [comment]
You're right. I've forgot to `push`.

**Comment by Jorengarenar** [comment]
You're right. I've forgotten to `push`.
