### ISSUE TITLE
Installation guide typo?

### ISSUE THREAD

**Issue by ggadget6** [Jorengarenar/minPlug#3]
The installation guide recommends running this command to install minPlug:
**git clone https://github.com/Jorengarenar/minPlug.git ~/.vim/pack/plugin/opt/minPlug/**

Shouldn't it be ~/.vim/pack/plugins, not plugin? If I'm wrong please let me know, I just noticed that now I have a plugin and a plugins directory in my .vim directory

**Comment by Jorengarenar** [comment]
Indeed, thank you for pointing this out.
