### ISSUE TITLE
MinPlug doesn't work in runtimepath/plugin/*.vim

### ISSUE THREAD

**Issue by palb91** [Jorengarenar/minPlug#4]
Hi!
Beautiful little plugin :)
I met a problem, it's possible that I misunderstood something with vim itself.

In my vimrc, I have the following:
```vim
set runtimepath^=$XDG_CONFIG_HOME/vim
set packpath^=$XDG_DATA_HOME/vim
```
So I can split some parts of my config in `$XDG_CONFIG_HOME/vim/plugin/**/*.vim`

If I write the following code in my vimrc, everything works well (after a `MinPlugInstall`):
```vim
packadd minPlug
MinPlug ajh17/VimCompletesMe
```

However the same code in `$XDG_CONFIG_HOME/vim/plugin/pack.vim` doesn't work, but I can do `packadd VimCompletesMe`.

I know the file `pack.vim` is sourced, if I add `echo 'test'` in the file, I can see it on vim startup.
____
To reproduce, here are 3 simple tests (in vim, just press <kbd>i</kbd><kbd>/</kbd><kbd>Tab</kbd>, file completion should start):
<details>
  <summary><b>Test1</b>: everything in the <code>vimrc</code> file, it works.</summary>
  <pre>
VIMDIR=/tmp/vimtest
REPO='https://github.com/Jorengarenar/minPlug.git'
VIMINIT=":source ${VIMDIR}/vimrc"
rm -rf "${VIMDIR}"
mkdir -p -- "${VIMDIR}"
git clone --depth=1 "${REPO}" "${VIMDIR}"/pack/plugins/opt/minPlug/
echo "set packpath^=${VIMDIR}"      >> "${VIMDIR}"/vimrc
echo "packadd minPlug"              >> "${VIMDIR}"/vimrc
echo "MinPlug ajh17/VimCompletesMe" >> "${VIMDIR}"/vimrc
vim +MinPlugInstall +q
vim</pre>
</details>
<details>
  <summary><b>Test2:</b> Splitted in <code>vimrc</code> and <code>plugin/</code>, it fails.</summary>
  <pre>
VIMDIR=/tmp/vimtest
REPO='https://github.com/Jorengarenar/minPlug.git'
VIMINIT=":source ${VIMDIR}/vimrc"
rm -rf "${VIMDIR}"
mkdir -p -- "${VIMDIR}"/plugin
git clone --depth=1 "${REPO}" "${VIMDIR}"/pack/plugins/opt/minPlug/
echo "set runtimepath^=${VIMDIR}"   >> "${VIMDIR}"/vimrc
echo "set packpath^=${VIMDIR}"      >> "${VIMDIR}"/vimrc
echo 'packadd minPlug'              >> "${VIMDIR}"/plugin/pack.vim
echo 'MinPlug ajh17/VimCompletesMe' >> "${VIMDIR}"/plugin/pack.vim
vim +MinPlugInstall +q
vim</pre>
</details>
<details>
  <summary><b>Test3:</b> Splitted, but with `packadd VimCompletesMe`, it works</summary>
  <pre>
VIMDIR=/tmp/vimtest
REPO='https://github.com/Jorengarenar/minPlug.git'
VIMINIT=":source ${VIMDIR}/vimrc"
rm -rf "${VIMDIR}"
mkdir -p -- "${VIMDIR}"/plugin
git clone --depth=1 "${REPO}" "${VIMDIR}"/pack/plugins/opt/minPlug/
echo "set runtimepath^=${VIMDIR}"   >> "${VIMDIR}"/vimrc
echo "set packpath^=${VIMDIR}"      >> "${VIMDIR}"/vimrc
echo 'packadd minPlug'              >> "${VIMDIR}"/plugin/pack.vim
echo 'MinPlug ajh17/VimCompletesMe' >> "${VIMDIR}"/plugin/pack.vim
vim +MinPlugInstall +q
# To avoid error, packadd after installation
echo 'packadd VimCompletesMe'       >> "${VIMDIR}"/plugin/pack.vim
vim</pre>
</details>

Is it some vim behavior that I misunderstood? Am I doing something wrong? It's the first time that I meet such problem with a split configuration. Thanks in advance.
____
**OS:** ArchLinux
**Vim:** 8.2 (from extra/vim)
**minPlug:** master (commit 656e2d4eb7568660f582268444e33fab2e2c6d6c)

**Comment by Jorengarenar** [comment]
Does adding the following to _vimrc_ after `" XDG standards` section changes anything?
```vim
set nocompatible
filetype plugin indent on
```

**Comment by Jorengarenar** [comment]
It happens because part of your configuration is treated as plugins. Instead I recommend to add  at the end of _vimrc_:
```vim
runtime! vimrc.d/*.vim
autocmd VimEnter * ++once runtime! after/vimrc.d/*.vim
```
And using directory `vimrc.d` instead of `plugin`.

Alternatively, I've just added `g:minPlug_paBang`. If you `let g:minPlug_paBang=""`, it will work with `plugin/` too (although something else may break).

---

PS. Have you read [Make Vim follow XDG Base Directory specification](https://blog.joren.ga/configuring/vim-xdg)?

**Comment by palb91** [comment]
Hi!
No I never read your blog page, but thanks for sharing. I already have something close from what you did, but I missed some points, I will adapt my vimrc soon. 

*By the way Archlinux automatically set some settings to use XDG_CACHE_HOME: [archlinux.vim](https://github.com/archlinux/svntogit-packages/blob/packages/vim/trunk/archlinux.vim).*

I think I will use your first tip (using `vimrc.d/*`), I don't want to dig into broken things with new plugins. Thanks for your answer!
